apiVersion: v1
kind: Service
metadata:
    name: "testingaks-1bd0"
    labels:
        app: "testingaks-1bd0"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "testingaks-1bd0"